dist/Debug/GNU-Linux/qos-sse tests/extreme-delete.txt 2 > results/extreme-delete-2.txt
dist/Debug/GNU-Linux/qos-sse tests/extreme-delete.txt 4 > results/extreme-delete-4.txt
dist/Debug/GNU-Linux/qos-sse tests/extreme-delete.txt 8 > results/extreme-delete-8.txt
dist/Debug/GNU-Linux/qos-sse tests/extreme-delete.txt 16 > results/extreme-delete-16.txt
dist/Debug/GNU-Linux/qos-sse tests/extreme-delete.txt 32 > results/extreme-delete-32.txt
dist/Debug/GNU-Linux/qos-sse tests/extreme-delete.txt 64 > results/extreme-delete-64.txt
dist/Debug/GNU-Linux/qos-sse tests/extreme-delete.txt 128 > results/extreme-delete-128.txt
dist/Debug/GNU-Linux/qos-sse tests/extreme-delete.txt 256 > results/extreme-delete-256.txt
dist/Debug/GNU-Linux/qos-sse tests/extreme-delete.txt 512 > results/extreme-delete-512.txt
dist/Debug/GNU-Linux/qos-sse tests/extreme-delete.txt 1024 > results/extreme-delete-1024.txt
dist/Debug/GNU-Linux/qos-sse tests/extreme-delete.txt 2048 > results/extreme-delete-2048.txt
dist/Debug/GNU-Linux/qos-sse tests/extreme-delete.txt 4096 > results/extreme-delete-4096.txt
dist/Debug/GNU-Linux/qos-sse tests/extreme-delete.txt 8192 > results/extreme-delete-8192.txt
dist/Debug/GNU-Linux/qos-sse tests/extreme-delete.txt 16384 > results/extreme-delete-16384.txt
dist/Debug/GNU-Linux/qos-sse tests/extreme-delete.txt 32768 > results/extreme-delete-32768.txt
dist/Debug/GNU-Linux/qos-sse tests/extreme-delete.txt 65536 > results/extreme-delete-65536.txt
dist/Debug/GNU-Linux/qos-sse tests/extreme-delete.txt 131072 > results/extreme-delete-131072.txt
